version: '3'
services:
  jupyter:
    build: ./jupyter_tensorflow_tensorboard/
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work/
  mongo:
    image: mongo
    ports:
      - "27017:27017"
